//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechVeo.Api.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechVeo.Api.Domain.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payment amount is not equal to the video total amount..
        /// </summary>
        public static string Video_AmountIsNotEqualVideoAmount {
            get {
                return ResourceManager.GetString("Video_AmountIsNotEqualVideoAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot add items to an video that is not in the Pending status..
        /// </summary>
        public static string Video_CannotAddItemToNonPendingStatus {
            get {
                return ResourceManager.GetString("Video_CannotAddItemToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot apply discount to an video that is not in the Pending status..
        /// </summary>
        public static string Video_CannotApplyDiscountToNonPendingStatus {
            get {
                return ResourceManager.GetString("Video_CannotApplyDiscountToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot deliver an video that is not in the Ready status..
        /// </summary>
        public static string Video_CannotDeliverToNonReadyStatus {
            get {
                return ResourceManager.GetString("Video_CannotDeliverToNonReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot prepare an video that is not in the Received status..
        /// </summary>
        public static string Video_CannotPrepareToNonReceivedStatus {
            get {
                return ResourceManager.GetString("Video_CannotPrepareToNonReceivedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot ready an video that is not in the InPreparation status..
        /// </summary>
        public static string Video_CannotReadyToNonInPreparationStatus {
            get {
                return ResourceManager.GetString("Video_CannotReadyToNonInPreparationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot receive an video that is not in the Pending status..
        /// </summary>
        public static string Video_CannotReceiveToNonPendingStatus {
            get {
                return ResourceManager.GetString("Video_CannotReceiveToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot remove items from an video that is not in the Pending status..
        /// </summary>
        public static string Video_CannotRemoveItemToNonPendingStatus {
            get {
                return ResourceManager.GetString("Video_CannotRemoveItemToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Discount cannot be negative..
        /// </summary>
        public static string Video_DiscountCannotBeNegative {
            get {
                return ResourceManager.GetString("Video_DiscountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video item not found..
        /// </summary>
        public static string Video_ItemNotFound {
            get {
                return ResourceManager.GetString("Video_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payment cannot be null..
        /// </summary>
        public static string Video_PaymentIsNull {
            get {
                return ResourceManager.GetString("Video_PaymentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ProductId is not valid.
        /// </summary>
        public static string VideoItem_ThrowProductIdIsInvalid {
            get {
                return ResourceManager.GetString("VideoItem_ThrowProductIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The OrdemItem quantity have be greater than zero.
        /// </summary>
        public static string VideoItem_ThrowQuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("VideoItem_ThrowQuantityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The videoItem UnitPrice have be greater than zero.
        /// </summary>
        public static string VideoItem_ThrowUnitPriceGreaterThanZero {
            get {
                return ResourceManager.GetString("VideoItem_ThrowUnitPriceGreaterThanZero", resourceCulture);
            }
        }
    }
}
