//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechVeo.Management.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechVeo.Management.Domain.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payment amount is not equal to the management total amount..
        /// </summary>
        public static string Management_AmountIsNotEqualManagementAmount {
            get {
                return ResourceManager.GetString("Management_AmountIsNotEqualManagementAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot add items to an management that is not in the Pending status..
        /// </summary>
        public static string Management_CannotAddItemToNonPendingStatus {
            get {
                return ResourceManager.GetString("Management_CannotAddItemToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot apply discount to an management that is not in the Pending status..
        /// </summary>
        public static string Management_CannotApplyDiscountToNonPendingStatus {
            get {
                return ResourceManager.GetString("Management_CannotApplyDiscountToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot deliver an management that is not in the Ready status..
        /// </summary>
        public static string Management_CannotDeliverToNonReadyStatus {
            get {
                return ResourceManager.GetString("Management_CannotDeliverToNonReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot prepare an management that is not in the Received status..
        /// </summary>
        public static string Management_CannotPrepareToNonReceivedStatus {
            get {
                return ResourceManager.GetString("Management_CannotPrepareToNonReceivedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot ready an management that is not in the InPreparation status..
        /// </summary>
        public static string Management_CannotReadyToNonInPreparationStatus {
            get {
                return ResourceManager.GetString("Management_CannotReadyToNonInPreparationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot receive an management that is not in the Pending status..
        /// </summary>
        public static string Management_CannotReceiveToNonPendingStatus {
            get {
                return ResourceManager.GetString("Management_CannotReceiveToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot remove items from an management that is not in the Pending status..
        /// </summary>
        public static string Management_CannotRemoveItemToNonPendingStatus {
            get {
                return ResourceManager.GetString("Management_CannotRemoveItemToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Discount cannot be negative..
        /// </summary>
        public static string Management_DiscountCannotBeNegative {
            get {
                return ResourceManager.GetString("Management_DiscountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Management item not found..
        /// </summary>
        public static string Management_ItemNotFound {
            get {
                return ResourceManager.GetString("Management_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payment cannot be null..
        /// </summary>
        public static string Management_PaymentIsNull {
            get {
                return ResourceManager.GetString("Management_PaymentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ProductId is not valid.
        /// </summary>
        public static string ManagementItem_ThrowProductIdIsInvalid {
            get {
                return ResourceManager.GetString("ManagementItem_ThrowProductIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The OrdemItem quantity have be greater than zero.
        /// </summary>
        public static string ManagementItem_ThrowQuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("ManagementItem_ThrowQuantityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The managementItem UnitPrice have be greater than zero.
        /// </summary>
        public static string ManagementItem_ThrowUnitPriceGreaterThanZero {
            get {
                return ResourceManager.GetString("ManagementItem_ThrowUnitPriceGreaterThanZero", resourceCulture);
            }
        }
    }
}
